
[general]
email = "your-email@example.com"

[postgres]
host = "your-db-host"
port = "5432"
dbname = "your-db-name"
user = "your-db-user"
password = "your-db-password"

[encryption]
key = "your-base64-encoded-aes256-key"
